package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

const (
	defaultCIWorkflowPath       = ".github/workflows/stagehand.yml"
	defaultPublishedActionRef   = "stagehand/stagehand-action@v0"
	defaultLocalActionReference = "./"
)

func runCI(args []string, stdout io.Writer, stderr io.Writer) error {
	if len(args) == 0 {
		return fmt.Errorf("ci requires a subcommand\n\n%s", ciHelpText())
	}
	switch args[0] {
	case "-h", "--help", "help":
		_, _ = io.WriteString(stdout, ciHelpText())
		return nil
	case "setup":
		return runCISetup(args[1:], stdout, stderr)
	default:
		return fmt.Errorf("unknown ci subcommand %q\n\n%s", args[0], ciHelpText())
	}
}

func runCISetup(args []string, stdout io.Writer, _ io.Writer) error {
	flags := flag.NewFlagSet("ci setup", flag.ContinueOnError)
	flags.SetOutput(io.Discard)

	outputPath := flags.String("output", defaultCIWorkflowPath, "Path to write the GitHub Actions workflow")
	command := flags.String("command", "", "Command to run under Stagehand replay")
	session := flags.String("session", "", "Stagehand session whose latest baseline should be used")
	configPath := flags.String("config", defaultRuntimeConfigPath, "Path to stagehand.yml")
	assertionsPath := flags.String("assertions", "assertions.yml", "Path to Stagehand assertions YAML")
	artifactName := flags.String("artifact-name", "stagehand-run", "GitHub Actions artifact name")
	commentID := flags.String("comment-id", "stagehand-main", "Stable PR comment identifier")
	actionRef := flags.String("action-ref", defaultLocalActionReference, "Action reference to use in the workflow")
	published := flags.Bool("published", false, "Use the published Stagehand action reference")
	dryRun := flags.Bool("dry-run", false, "Print the workflow without writing it")
	force := flags.Bool("force", false, "Overwrite an existing workflow file")
	if err := flags.Parse(args); err != nil {
		return fmt.Errorf("parse ci setup flags: %w\n\n%s", err, ciSetupHelpText())
	}
	if len(flags.Args()) > 0 {
		return fmt.Errorf("ci setup does not accept positional arguments\n\n%s", ciSetupHelpText())
	}

	resolvedCommand := strings.TrimSpace(*command)
	resolvedSession := strings.TrimSpace(*session)
	if resolvedCommand == "" || resolvedSession == "" {
		info := detectInitProject(mustGetwd())
		if resolvedCommand == "" {
			resolvedCommand = "python agent.py"
			if len(info.Commands) > 0 {
				resolvedCommand = info.Commands[0]
			}
		}
		if resolvedSession == "" {
			resolvedSession = defaultRecordBaselineSession()
		}
	}
	resolvedActionRef := strings.TrimSpace(*actionRef)
	if *published {
		resolvedActionRef = defaultPublishedActionRef
	}
	if resolvedActionRef == "" {
		resolvedActionRef = defaultLocalActionReference
	}

	workflow := renderCIWorkflow(ciWorkflowOptions{
		Command:        resolvedCommand,
		Session:        resolvedSession,
		ConfigPath:     firstNonEmpty(*configPath, defaultRuntimeConfigPath),
		AssertionsPath: firstNonEmpty(*assertionsPath, "assertions.yml"),
		ArtifactName:   firstNonEmpty(*artifactName, "stagehand-run"),
		CommentID:      firstNonEmpty(*commentID, "stagehand-main"),
		ActionRef:      resolvedActionRef,
		LocalAction:    resolvedActionRef == defaultLocalActionReference,
	})

	if *dryRun {
		_, err := io.WriteString(stdout, workflow)
		return err
	}

	path := firstNonEmpty(*outputPath, defaultCIWorkflowPath)
	if fileExists(path) && !*force {
		return fmt.Errorf("refusing to overwrite existing workflow %q; rerun with --force to replace it", path)
	}
	if err := os.MkdirAll(filepath.Dir(filepath.Clean(path)), 0o755); err != nil {
		return fmt.Errorf("create workflow directory for %q: %w", path, err)
	}
	if err := os.WriteFile(path, []byte(workflow), 0o644); err != nil {
		return fmt.Errorf("write workflow %q: %w", path, err)
	}
	_, err := fmt.Fprintf(stdout, "Stagehand CI workflow written to %s\n\nBefore enabling PR enforcement, record and promote a baseline:\n  stagehand record-baseline --session %s -- %s\n\n", filepath.ToSlash(path), resolvedSession, resolvedCommand)
	return err
}

type ciWorkflowOptions struct {
	Command        string
	Session        string
	ConfigPath     string
	AssertionsPath string
	ArtifactName   string
	CommentID      string
	ActionRef      string
	LocalAction    bool
}

func renderCIWorkflow(opts ciWorkflowOptions) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `stagehand ci setup`.\n")
	fmt.Fprintf(&b, "# Before enabling PR enforcement, run locally and commit the resulting baseline store/artifacts you intend CI to use:\n")
	fmt.Fprintf(&b, "#   stagehand record-baseline --session %s -- %s\n", opts.Session, opts.Command)
	fmt.Fprintf(&b, "# Keep `uses: ./` while using the repository-local unpublished action. After release, switch to `%s` or run with `--published`.\n", defaultPublishedActionRef)
	fmt.Fprintf(&b, "\n")
	fmt.Fprintf(&b, "name: Stagehand\n\n")
	fmt.Fprintf(&b, "on:\n")
	fmt.Fprintf(&b, "  pull_request:\n")
	fmt.Fprintf(&b, "  workflow_dispatch:\n\n")
	fmt.Fprintf(&b, "permissions:\n")
	fmt.Fprintf(&b, "  contents: read\n")
	fmt.Fprintf(&b, "  pull-requests: write\n")
	fmt.Fprintf(&b, "  issues: write\n")
	fmt.Fprintf(&b, "  actions: read\n\n")
	fmt.Fprintf(&b, "jobs:\n")
	fmt.Fprintf(&b, "  replay-diff:\n")
	fmt.Fprintf(&b, "    runs-on: ubuntu-latest\n")
	fmt.Fprintf(&b, "    steps:\n")
	fmt.Fprintf(&b, "      - uses: actions/checkout@v4\n\n")
	if opts.LocalAction {
		fmt.Fprintf(&b, "      - uses: actions/setup-go@v5\n")
		fmt.Fprintf(&b, "        with:\n")
		fmt.Fprintf(&b, "          go-version-file: go.mod\n\n")
		fmt.Fprintf(&b, "      - run: go build -o bin/stagehand ./cmd/stagehand\n\n")
	} else {
		fmt.Fprintf(&b, "      # Install or download the Stagehand CLI here when using the published action.\n")
		fmt.Fprintf(&b, "      # The action expects the binary at bin/stagehand unless stagehand-binary is overridden.\n\n")
	}
	fmt.Fprintf(&b, "      - name: Stagehand replay and diff\n")
	fmt.Fprintf(&b, "        uses: %s\n", opts.ActionRef)
	fmt.Fprintf(&b, "        env:\n")
	fmt.Fprintf(&b, "          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}\n")
	fmt.Fprintf(&b, "          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}\n")
	fmt.Fprintf(&b, "          # Add internal service credentials as needed, for example:\n")
	fmt.Fprintf(&b, "          # INTERNAL_API_TOKEN: ${{ secrets.INTERNAL_API_TOKEN }}\n")
	fmt.Fprintf(&b, "        with:\n")
	fmt.Fprintf(&b, "          command: %s\n", opts.Command)
	fmt.Fprintf(&b, "          sessions: %s\n", opts.Session)
	fmt.Fprintf(&b, "          config: %s\n", opts.ConfigPath)
	fmt.Fprintf(&b, "          test-config: stagehand.test.yml\n")
	fmt.Fprintf(&b, "          baseline-source: latest\n")
	fmt.Fprintf(&b, "          report-format: github-markdown\n")
	fmt.Fprintf(&b, "          fail-on: |\n")
	fmt.Fprintf(&b, "            behavior_diff\n")
	fmt.Fprintf(&b, "            assertion_failure\n")
	fmt.Fprintf(&b, "            fallback_regression\n")
	fmt.Fprintf(&b, "          assertions: %s\n", opts.AssertionsPath)
	fmt.Fprintf(&b, "          upload-artifact: 'true'\n")
	fmt.Fprintf(&b, "          artifact-paths: |\n")
	fmt.Fprintf(&b, "            .stagehand/runs\n")
	fmt.Fprintf(&b, "            .stagehand/reports\n")
	fmt.Fprintf(&b, "          artifact-name: %s\n", opts.ArtifactName)
	fmt.Fprintf(&b, "          post-pr-comment: 'true'\n")
	fmt.Fprintf(&b, "          comment-id: %s\n", opts.CommentID)
	fmt.Fprintf(&b, "          github-token: ${{ secrets.GITHUB_TOKEN }}\n")
	return b.String()
}

func ciHelpText() string {
	return `Usage:
  stagehand ci <subcommand> [flags]

Subcommands:
  setup  Generate a GitHub Actions workflow for Stagehand
`
}

func ciSetupHelpText() string {
	return `Usage:
  stagehand ci setup [flags]

Flags:
  --output string         Workflow path (default: .github/workflows/stagehand.yml)
  --command string        Command to run under Stagehand replay
  --session string        Stagehand session whose latest baseline should be used
  --config string         Path to stagehand.yml (default: stagehand.yml)
  --assertions string     Path to assertions YAML (default: assertions.yml)
  --artifact-name string  GitHub Actions artifact name (default: stagehand-run)
  --comment-id string     Stable PR comment identifier (default: stagehand-main)
  --action-ref string     Action reference to use (default: ./)
  --published             Use stagehand/stagehand-action@v0
  --dry-run               Print workflow without writing it
  --force                 Overwrite existing workflow
`
}
